# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'KlivvrSocialAppIOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  # Pods for KlivvrSocialAppIOS

  target 'KlivvrSocialAppIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KlivvrSocialAppIOSUITests' do
    # Pods for testing
  end

end
